#!/usr/bin/env python

# Copyright 2025 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from huggingface_hub import hf_hub_download


def resolve_hf_path(path: str | Path) -> Path:
    """Resolve a path that may be a HuggingFace URL (hf://datasets/...) to a local path."""
    path_str = str(path)
    if path_str.startswith("hf://datasets/"):
        parts = path_str.replace("hf://datasets/", "").split("/")
        repo_id = "/".join(parts[:2])
        filename = "/".join(parts[2:])
        return Path(hf_hub_download(repo_id=repo_id, filename=filename, repo_type="dataset"))
    return Path(path)


class RABCWeights:
    """
    Load precomputed SARM progress values and compute RA-BC weights during training.

    Progress values are loaded from a parquet file (generated by compute_rabc_weights.py).
    During training, computes:
        - progress_delta = progress[t + chunk_size] - progress[t]
        - rabc_weight based on the delta (paper Eq. 8-9)

    Args:
        progress_path: Path to parquet file with precomputed progress values
        chunk_size: Number of frames ahead for computing progress delta
        head_mode: Which SARM head to use ("sparse" or "dense")
        kappa: Hard threshold for high-quality samples (default: 0.01)
        epsilon: Small constant for numerical stability (default: 1e-6)
        fallback_weight: Weight to use for frames without valid delta (default: 1.0)
        device: Device to return tensors on
    """

    def __init__(
        self,
        progress_path: str | Path,
        chunk_size: int = 50,
        head_mode: str = "sparse",
        kappa: float = 0.01,
        epsilon: float = 1e-6,
        fallback_weight: float = 1.0,
        device: torch.device = None,
        weighting_mode: str = "rabc",
        length_adaptive_gain: bool = False,
        awbc_ref_length: float | None = None,
        gain_clip_min: float = 0.25,
        gain_clip_max: float = 4.0,
    ):
        self.progress_path = resolve_hf_path(progress_path)
        self.chunk_size = chunk_size
        self.head_mode = head_mode
        self.kappa = kappa
        self.epsilon = epsilon
        self.fallback_weight = fallback_weight
        self.device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.weighting_mode = weighting_mode.lower()
        if self.weighting_mode not in {"rabc", "awbc"}:
            raise ValueError(f"weighting_mode must be 'rabc' or 'awbc', got {weighting_mode}")
        self.length_adaptive_gain = bool(length_adaptive_gain or self.weighting_mode == "awbc")
        self.gain_clip_min = float(gain_clip_min)
        self.gain_clip_max = float(gain_clip_max)
        if self.gain_clip_min <= 0 or self.gain_clip_max <= 0:
            raise ValueError("gain_clip_min and gain_clip_max must be > 0")
        if self.gain_clip_min > self.gain_clip_max:
            raise ValueError("gain_clip_min must be <= gain_clip_max")

        self.progress_column = f"progress_{head_mode}"
        logging.info(f"Loading SARM progress values from {self.progress_path}")
        self.df = pd.read_parquet(self.progress_path)

        if self.progress_column not in self.df.columns:
            available = [c for c in self.df.columns if c.startswith("progress")]
            raise ValueError(
                f"Column '{self.progress_column}' not found. Available progress columns: {available}"
            )

        logging.info(f"Using progress column: {self.progress_column}")
        logging.info(
            f"RA-BC weighting mode: {self.weighting_mode} (length_adaptive_gain={self.length_adaptive_gain})"
        )

        self.progress_lookup: dict[int, float] = {}
        self.episode_lookup: dict[int, int] = {}
        for _, row in self.df.iterrows():
            global_idx = int(row["index"])
            progress = row[self.progress_column]
            episode_idx = int(row["episode_index"])
            if not np.isnan(progress):
                self.progress_lookup[global_idx] = float(progress)
            self.episode_lookup[global_idx] = episode_idx

        self.episode_boundaries: dict[int, dict[str, int]] = {}
        self.episode_lengths: dict[int, int] = {}
        for episode_idx in self.df["episode_index"].unique():
            ep_df = self.df[self.df["episode_index"] == episode_idx]
            start = int(ep_df["index"].min())
            end = int(ep_df["index"].max()) + 1
            self.episode_boundaries[int(episode_idx)] = {"start": start, "end": end}
            if "episode_length" in ep_df.columns:
                self.episode_lengths[int(episode_idx)] = int(ep_df["episode_length"].iloc[0])
            else:
                self.episode_lengths[int(episode_idx)] = end - start

        if awbc_ref_length is not None:
            self.ref_length = max(float(awbc_ref_length), 1.0)
        elif self.episode_lengths:
            self.ref_length = max(float(np.mean(list(self.episode_lengths.values()))), 1.0)
        else:
            self.ref_length = 1.0

        logging.info(f"Loaded {len(self.progress_lookup)} frame progress values")
        logging.info(f"Chunk size for delta computation: {chunk_size}")
        if self.length_adaptive_gain:
            logging.info(f"AW-BC reference sequence length: {self.ref_length:.2f}")
        self._compute_global_stats()

    def _compute_global_stats(self):
        """Compute global mean/std for effective deltas used by weighting."""
        all_effective_deltas = []
        all_gains = []
        for global_idx in self.progress_lookup:
            delta = self._compute_delta(global_idx)
            if np.isnan(delta):
                continue
            gain = self._compute_gain(global_idx)
            effective_delta = delta * gain if self.length_adaptive_gain else delta
            if np.isnan(effective_delta):
                continue
            all_effective_deltas.append(effective_delta)
            all_gains.append(gain)

        if all_effective_deltas:
            self.delta_mean = max(float(np.mean(all_effective_deltas)), 0.0)
            self.delta_std = max(float(np.std(all_effective_deltas)), self.epsilon)
            self.gain_mean = float(np.mean(all_gains)) if all_gains else 1.0
            logging.info(
                f"Effective delta stats: mean={self.delta_mean:.4f}, std={self.delta_std:.4f}, "
                f"mean_gain={self.gain_mean:.4f}"
            )
        else:
            self.delta_mean = 0.0
            self.delta_std = self.epsilon
            self.gain_mean = 1.0
            logging.warning("No valid progress deltas found, using default stats")

    def compute_batch_weights(self, batch: dict) -> tuple[torch.Tensor, dict]:
        """Compute RA-BC/AW-BC weights for a batch."""
        indices = batch.get("index")
        if indices is None:
            logging.warning("RA-BC: Batch missing 'index' key, using uniform weights")
            batch_size = self._get_batch_size(batch)
            ones = torch.ones(batch_size, device=self.device)
            return ones, {"raw_mean_weight": 1.0, "raw_mean_gain": 1.0}

        if isinstance(indices, torch.Tensor):
            indices = indices.cpu().numpy().tolist()
        elif isinstance(indices, np.ndarray):
            indices = indices.tolist()

        gains = []
        effective_deltas = []
        for idx in indices:
            global_idx = int(idx)
            delta = self._compute_delta(global_idx)
            gain = self._compute_gain(global_idx)
            gains.append(gain)
            if np.isnan(delta):
                effective_deltas.append(np.nan)
            else:
                effective_deltas.append(delta * gain if self.length_adaptive_gain else delta)

        effective_deltas = np.array(effective_deltas, dtype=np.float32)
        gains = np.array(gains, dtype=np.float32)
        weights = self._compute_weights(effective_deltas)

        raw_mean_weight = float(np.nanmean(weights))
        num_zero_weight = int(np.sum(weights == 0))
        num_full_weight = int(np.sum(weights == 1.0))
        valid_gain = gains[~np.isnan(gains)]
        raw_mean_gain = float(np.mean(valid_gain)) if valid_gain.size > 0 else 1.0
        batch_stats = {
            "raw_mean_weight": raw_mean_weight,
            "num_zero_weight": num_zero_weight,
            "num_full_weight": num_full_weight,
            "raw_mean_gain": raw_mean_gain,
        }

        weights = torch.tensor(weights, device=self.device, dtype=torch.float32)
        batch_size = len(weights)
        weight_sum = weights.sum() + self.epsilon
        weights = weights * batch_size / weight_sum
        return weights, batch_stats

    def _compute_delta(self, global_idx: int) -> float:
        """Compute raw progress delta for a single frame."""
        current_progress = self.progress_lookup.get(global_idx)
        if current_progress is None:
            return np.nan

        episode_idx = self.episode_lookup.get(global_idx)
        if episode_idx is None:
            return np.nan

        bounds = self.episode_boundaries.get(episode_idx)
        if bounds is None:
            return np.nan

        future_idx = global_idx + self.chunk_size
        if future_idx >= bounds["end"]:
            future_idx = bounds["end"] - 1

        future_progress = self.progress_lookup.get(future_idx)
        if future_progress is None:
            return np.nan
        return future_progress - current_progress

    def _compute_gain(self, global_idx: int) -> float:
        """Compute AW-BC length-adaptive gain for a frame."""
        if not self.length_adaptive_gain:
            return 1.0
        episode_idx = self.episode_lookup.get(global_idx)
        if episode_idx is None:
            return 1.0
        seq_len = float(self.episode_lengths.get(episode_idx, 0))
        if seq_len <= 0:
            return 1.0
        gain = seq_len / max(self.ref_length, self.epsilon)
        return float(np.clip(gain, self.gain_clip_min, self.gain_clip_max))

    def _compute_weights(self, deltas: np.ndarray) -> np.ndarray:
        """Compute sample weights from effective progress deltas (Eq. 8-9)."""
        valid_mask = ~np.isnan(deltas)
        lower_bound = self.delta_mean - 2 * self.delta_std
        soft_weights = (deltas - lower_bound) / (4 * self.delta_std + self.epsilon)
        soft_weights = np.clip(soft_weights, 0.0, 1.0)

        weights = np.zeros_like(deltas, dtype=np.float32)
        high_quality_mask = deltas > self.kappa
        weights[high_quality_mask] = 1.0
        moderate_mask = (deltas >= 0) & (deltas <= self.kappa)
        weights[moderate_mask] = soft_weights[moderate_mask]
        weights[~valid_mask] = self.fallback_weight
        return weights

    def _get_batch_size(self, batch: dict) -> int:
        for key in ["action", "index"]:
            if key in batch:
                val = batch[key]
                if isinstance(val, (torch.Tensor, np.ndarray)):
                    return val.shape[0]
        return 1

    def get_stats(self) -> dict:
        return {
            "num_frames": len(self.progress_lookup),
            "chunk_size": self.chunk_size,
            "head_mode": self.head_mode,
            "delta_mean": self.delta_mean,
            "delta_std": self.delta_std,
            "kappa": self.kappa,
            "weighting_mode": self.weighting_mode,
            "length_adaptive_gain": self.length_adaptive_gain,
            "ref_length": self.ref_length,
            "gain_mean": self.gain_mean,
        }
